### ISSUE TITLE
machine_manager: manufacturer cannot be entered manually 

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#1081] opened 2015-11-23 12:33 UTC
I guess it was meant to be a feature, the fact that the manufacturer can only be entered in the product. It's only that if you create the machine manually, you may not necessarily associate it with a product and therefore would be nevertheless interested in having the manufacturer on it.

Thanks for your answer

eva P.

**Comment by pedrobaeza** [comment] 2015-11-23 12:46
@anajuaristi, opinion? I see no problem at first sight.

**Comment by anajuaristi** [comment] 2015-11-23 22:04
It's not a bug.
It has been designed like that after a heavy discussion we had on desing.

If we open the possibility of having manual manufacturer on machine, User has to assure the data integrity between product manufacturer and machine manufacturer so we think it's easier don't let that concern in users hand.
This way integrity will not be broken.

Usually a machine will be related to a product otherwise you can not link with a serial number, invoice or any other product related field.

**Comment by pedrobaeza** [comment] 2015-11-23 22:19
OK, that makes sense, so I close it.

**Closed as completed by pedrobaeza** 2015-11-23 22:19 UTC
