### ISSUE TITLE
Instalation mrp_production_real_costs problem

### ISSUE THREAD

**Issue by vafonso** [odoomrp/odoomrp-wip#1087] opened 2015-11-29 17:39 UTC
Hi all,

This weekend  I did a pull to update my local repository from your odoomrp-wip and I did a completly new Odoo instalation.

After all done, when I tried to confirm a new worl order, I got the follwing error:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, _args)
  File "/opt/odoo/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, *_kw)
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3572, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 97, in action_confirm
    res = super(MrpProduction, self).action_confirm()
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_project_link/models/mrp_production.py", line 93, in action_confirm
    procurements.set_main_project()
ValueError: "'procurement.order' object has no attribute 'set_main_project'" while evaluating
u'action_confirm()'

Could you please check it?
Thanks in advance
Vinicius

**Comment by pedrobaeza** [comment] 2015-11-29 17:59
Thanks for reporting. Fixed in https://github.com/odoomrp/odoomrp-wip/commit/a179b3360b5afc26f881775b0b03907f570f8301

**Comment by vafonso** [comment] 2015-11-29 21:38
Hi Mr. Pedro, thank you for very fast fixing

Unfortunately, I've got now a new error:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/opt/odoo/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/opt/odoo/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, _args)
  File "/opt/odoo/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, *_kw)
  File "/opt/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3572, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 98, in action_confirm
    self.calculate_production_estimated_cost()
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 288, in calculate_production_estimated_cost
    record, product_line)
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 191, in _create_material_estimated_cost
    return self.env['account.analytic.line'].create(vals)
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4094, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 496, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4304, in _create
    recs.recompute()
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 5755, in recompute
    name: rec[name] for name in names
  File "/opt/odoo/openerp/models.py", line 5755, in <dictcomp>
    name: rec[name] for name in names
  File "/opt/odoo/openerp/models.py", line 5639, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/openerp/fields.py", line 819, in **get**
    self.determine_value(record)
  File "/opt/odoo/openerp/fields.py", line 897, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/openerp/fields.py", line 877, in compute_value
    self._compute_value(records)
  File "/opt/odoo/openerp/fields.py", line 869, in _compute_value
    self.compute(records)
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 431, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/localizacao/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 37, in get_unit_avg_cost
    self.analytic_line_ids]))
  File "/opt/odoo/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/opt/odoo/openerp/fields.py", line 912, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3243, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3180, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3367, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 784, in get
    result[int(record[inverse])].append(record.id)
ValueError: "False" while evaluating
u'action_confirm()'

Could you please be so kind to verify more it?

Thanks in advance

Kind regards

**Comment by pedrobaeza** [comment] 2015-11-30 00:18
That error is very strange and seems unrelated to the change. Please try to reproduce it on runbot instance: https://runbot.odoo-community.org/runbot/repo/github-com-odoomrp-odoomrp-wip-188

**Comment by vafonso** [comment] 2015-11-30 10:46
Hi Mr. Pedro
I enter on http://3136231-8-0-a179b3.runbot2.odoo-community.org/web?debug=1#id=7&view_type=form&model=mrp.production&menu_id=410&action=543 and I created two itens: Componente A and Acabado A. They are component and finish good respectively
After, I created  MO00007 and when you try to confirm production, you get the following error:

Odoo Server Error
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/web/controllers/main.py", line 955, in exec_workflow
    return request.session.exec_workflow(model, id, signal)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 1111, in exec_workflow
    r = self.proxy('object').exec_workflow(self.db, self.uid, self.password, model, signal, id)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 37, in dispatch
    res = fn(db, uid, _params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 188, in exec_workflow
    return exec_workflow_cr(cr, uid, obj, signal, _args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 182, in exec_workflow_cr
    return execute_cr(cr, uid, obj, 'signal_workflow', [res_id], signal)[res_id]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/service/model.py", line 164, in execute_cr
    return getattr(object, method)(cr, uid, *args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 3572, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/mrp_project_link_mto/models/mrp_production.py", line 14, in action_confirm
    result = super(MrpProduction, self).action_confirm()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/mrp_production_project_estimated_cost/models/mrp_production.py", line 98, in action_confirm
    self.calculate_production_estimated_cost()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/mrp_production_project_estimated_cost/models/mrp_production.py", line 288, in calculate_production_estimated_cost
    record, product_line)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/mrp_production_project_estimated_cost/models/mrp_production.py", line 191, in _create_material_estimated_cost
    return self.env['account.analytic.line'].create(vals)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 4094, in create
    record = self.browse(self._create(old_vals))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 496, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 4304, in _create
    recs.recompute()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 5755, in recompute
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 5755, in <dictcomp>
    name: rec[name] for name in names
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 5639, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 819, in **get**
    self.determine_value(record)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 897, in determine_value
    self.compute_value(recs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 877, in compute_value
    self._compute_value(records)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 869, in _compute_value
    self.compute(records)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 431, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/addons/mrp_production_project_estimated_cost/models/mrp_production.py", line 29, in get_unit_std_cost
    self.analytic_line_ids]))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/fields.py", line 912, in determine_value
    record._prefetch_field(self)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 3243, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 3180, in read
    self._read_from_database(stored, inherited)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/models.py", line 3367, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136231-8-0-a179b3/openerp/osv/fields.py", line 784, in get
    result[int(record[inverse])].append(record.id)
ValueError: "False" while evaluating
u'action_confirm()'

I also did some adjustments on Settings to reflect the situation that I had here
Please let me know if I am doing something wrong.

Thanks for your great support

Kind regards

Vinicius

**Comment by vafonso** [comment] 2015-12-01 11:44
Hi Pedro, how are you?

I've seen that today the instance  https://runbot.odoo-community.org/runbot/repo/github-com-odoomrp-odoomrp-wip-188 is working properly.
What should I do here to get the same behaviour? It was some wrong config that I did?
Thanks for your assistance

Kind regards
Vinicius

**Comment by anajuaristi** [comment] 2015-12-01 11:47
@valfonso ups... sorry
It has been me. 

I have just uninstalled the estimated_cost module to verify that error was caused by that module. So now it's working but... it should also work with module installed in any instance.

I have reported internally, so we will try to solve ASAP
@agaldona 

Sorry for inconvenience.

**Comment by agaldona** [comment] 2015-12-11 09:11
Fixed on the last version of Odoomrp-wip

**Closed as completed** 2015-12-11 09:11 UTC
Labels: bug
